#%RAML 1.0
title: vitech-bank- customer-acct-creation
description: API for bank customer account creation
version: v1
protocols:
  - HTTP
  - HTTPS
#securitySchemes:
#  secure: !include /Security Schema/securityScheme.raml
#securedBy:
#  - secure*

/createAccounts :
  post:
    queryParameters:
      CustomerName:
        required: true
        maxLength: 45
        minLength: 4
      Bank:
        enum:
          - ICICI
          - AXIS
          - HDFC
          - SBI
      Type:
        enum:
          - Savings
          - Current
      Branchname:
        required: true
        minLength: 4
        maxLength: 10
    body:
      application/json:
        type: !include /datatype/InputdataType.raml
        example: !include /examples/request/inputexample.raml
    responses:
      201:
        body:
          application/json:
            example: !include /examples/response/responseexample.raml
            
            


