name: MuleSoft CI/CD Pipeline

on:
  push:
    branches:
      - feature_release_1
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17 + Exchange login
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          server-id: anypoint-exchange-v3
          server-username: ANYPOINT_USER
          server-password: ANYPOINT_PWD

      - name: Set unique version
        run: mvn -B versions:set -DnewVersion=1.0.${{ github.run_number }} -DgenerateBackupPoms=false

      - name: Maven Build
        run: mvn clean package -DskipTests -B

      - name: Publish to Exchange
        env:
          ANYPOINT_USER: ${{ secrets.ANYPOINT_USER }}
          ANYPOINT_PWD: ${{ secrets.ANYPOINT_PWD }}
        run: mvn deploy -DskipTests -B

      - name: Deploy to CloudHub 2.0
        env:
          ANYPOINT_USER: ${{ secrets.ANYPOINT_USER }}
          ANYPOINT_PWD: ${{ secrets.ANYPOINT_PWD }}
        run: >
          mvn deploy -DskipTests -DmuleDeploy -B
          -Danypointusername="$ANYPOINT_USER"
          -Danypointpassword="$ANYPOINT_PWD"
